services:
  backend:
    build:
      context: ../../IS-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../IS-Backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
    depends_on:
      - database
    networks:
      - isteamx-network

  frontend:
    build:
      context: ../../IS-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - isteamx-network

  database:
    image: postgres:latest
    env_file:
      - ../../IS-Backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - isteamx-network

networks:
  isteamx-network:
    driver: bridge

volumes:
  postgres-data:
